### ISSUE TITLE
NullPointerException when http://localhost:8080/restcon/project and logged via Westlife-SSO

### ISSUE THREAD

**Issue by TomasKulhanek** [h2020-westlife-eu/wp6-repository#9]
This is caused by null projectService - i
List<Project> projects =projectService.findByUserId(user.getId());

When I log in using Spring user account - everithing is OK.
When is projectService instantiated?
--
HTTP ERROR 500

Problem accessing /restcon/project. Reason:

    Server Error

Caused by:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	
Caused by: java.lang.NullPointerException
	at org.cirmmp.spring.controller.RestCon.listProject(RestCon.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	... 72 more

**Comment by andreagia** [comment]
Hi Tomas in order to search the project belong the user I have to know the user information, these information normally in spring security project where managed by SecurityContextHolder class.
Using this String ssoId = SecurityContextHolder.getContext().getAuthentication().getName(); I'm able to retrive user information and perform the DB query:
 User user = userService.findBySSO(ssoId);
List<Project> projects =projectService.findByUserId(user.getId());
in RestCon.java 
Now I dont'have extended the http security filter on rest directories but in principle if you are not authenticated you are not be able to access to rest services and query DB.
 
Andrea

**Comment by andreagia** [comment]
I Tomas I have added comment on github request #9

**Comment by TomasKulhanek** [comment]
Thanks. I thought that nullpointer is caused by null projectService - but, it us null user thus user.getId() throws it.  Obviously, it doesn't exist in the database if it comes from Westlife-SSO - it needs to be managed. 

User authenticated from west-life SSO can be temporaryli created in the database with some default restrictive access. Repository Staff or Repository Admin can list these users and allow them better permission - create projects access files etc.

I'll be day off and back next week.
